---
driver_plugin: vagrant

driver_config:
  customize:
    memory: 1024

platforms:
- name: centos-6.5
  driver_config:
    box: opscode-centos-6.5
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box
    require_chef_omnibus: 11.16.2
- name: centos-7.0
  driver_config:
    box: opscode-centos-7.0
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.0_chef-provisionerless.box
    require_chef_omnibus: 11.16.2
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
    require_chef_omnibus: 11.16.2
- name: ubuntu-14.04
  driver_config:
    box: opscode-ubuntu-14.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
    require_chef_omnibus: 11.16.2

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[stash_test]
  attributes: {}
- name: apache2
  run_list:
  - recipe[minitest-handler]
  - recipe[stash_test::apache2]
  attributes: {}
